databases:
  - name: sen-mall_DB
    databaseName: sen_mall_db
    user: sen-mall
    region: singapore

services:
  - type: web
    name: sen-mall
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sen-mall_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

